dist: xenial
language: python
os: linux

python:
- "3.6"

if: branch = travis-ci

services:
  - docker

env:
- CHANGE_MINIKUBE_NONE_USER=true DISTRO_TYPE=upstream

before_install:
- hack/ci/install-deps

install:
- sudo minikube start --memory=4096 --vm-driver=none --kubernetes-version="v1.14.0" --extra-config=apiserver.v=10
- sudo chown -R $USER ${HOME}/.{mini,}kube
- kubectl config use-context minikube
- hack/ci/install-olm

jobs:
  include:
  - name: kubectl
    script:
    - hack/ci/test
#    - |-
#      kubectl get pods -n kube-system
#    - |-
#      cd ${TRAVIS_BUILD_DIR}/build && make k8s-deploy-olm-dev
#    - |-
#      cd ${TRAVIS_BUILD_DIR}/build && make k8s-undeploy-olm-dev
#    - |-
#      cd ${TRAVIS_BUILD_DIR}/build && make k8s-deploy-manual-dev
#    - |-
#      cd ${TRAVIS_BUILD_DIR}/build && make k8s-undeploy-manual-dev
#    - |-
#      git status 
#    - |-
#      docker images 
#    - |-
#      cd ../hack/ci/ && test