dist: xenial
language: python
os: linux

python:
- "3.6"

if: branch = travis-ci

env:
- CHANGE_MINIKUBE_NONE_USER=true

before_install:
- build/ci/install-deps

install:
- sudo minikube start --memory=4096 --vm-driver=none --kubernetes-version="v1.14.0" --extra-config=apiserver.v=10
- sudo chown -R $USER ${HOME}/.{mini,}kube
- kubectl config use-context minikube
- build/ci/install-olm
- eval $(sudo minikube docker-env)

jobs:
  include:
  - name: build
    script:
    - build/ci/build-dev
    - build/ci/test-dev
    - build/ci/release
    - build/ci/test
