version: 2.1
commands:
  install_golang:
    steps:
      - run:
          name: Install Golang v1.12.6
          command: |
            go get golang.org/dl/go1.12.6
            [ -e /home/circleci/sdk/go1.12.6 ] || go1.12.6 download
            go env
            echo "export GOPATH=/home/circleci/.go_workspace" | tee -a $BASH_ENV
            echo "export PATH=/home/circleci/sdk/go1.12.6/bin:\$PATH" | tee -a $BASH_ENV
  install_operator_sdk:
    steps:
      - run:
          name: Install Operators SDK Golang v1.12.6
          command: |
            export  RELEASE_VERSION=v0.12.0
            curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
            chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
  hack_build:
    steps:
      - run:
          name: Build Operator
          command: |
            cd /home/circleci/.go_workspace/src/github.com/disposab1e/argocd-operator-helm
            ls -la
            hack/build.sh
jobs:
  build:
    working_directory: /home/circleci/.go_workspace/src/github.com/disposab1e/argocd-operator-helm
    machine:
      image: circleci/classic:201808-01
    steps:
      - install_golang
      - install_operator_sdk
      - checkout
      - hack_build
    environment:
      GO111MODULE: "on"
workflows:
  version: 2
  build:
    jobs:
      - build
