version: 2.1
commands:
  install_operator_sdk:
    steps:
      - run:
          name: Install Operator Courier (latest)
          command: |
            export  RELEASE_VERSION=v0.12.0
            curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
            chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && mkdir -p /usr/local/bin/ && cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
  install_operator_courier:
    steps:
      - run:
          name: Install Operator Courier
          command: |
            pip3 install operator-courier
  build_bundle:
    steps:
      - run:
          name: Build Bundle
          command: |
            operator-courier --verbose verify /home/circleci/.go_workspace/src/github.com/disposab1e/argocd-operator-helm/deploy/olm-catalog/argocd-operator-helm
jobs:
  build:
    docker:
      - image: golang:1.12.13
    working_directory: /go/src/github.com/disposab1e/argocd-operator-helm
    environment:
      GO111MODULE: "on"
    steps:
      - setup_remote_docker:   # (2)
          version: 18.06.0-ce
          docker_layer_caching: false # (3)
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - install_operator_sdk
      - checkout
      - run: |
          ./hack/build.sh
      - run: |
          operator-sdk build disposab1e/argocd-operator-helm:0.0.2
  bundle:
    docker:
      - image: python:3.6.4
    working_directory: /go/src/github.com/disposab1e/argocd-operator-helm
    steps:
      - setup_remote_docker:   # (2)
          version: 18.06.0-ce
          docker_layer_caching: false # (3)
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - install_operator_courier
      - checkout
      - run: |
          operator-courier --verbose verify /go/src/github.com/disposab1e/argocd-operator-helm/deploy/olm-catalog/argocd-operator-helm
workflows:
  version: 2
  build:
    jobs:
      - build
      - bundle
