version: 2.1
jobs:
  build:
    machine: 
      image: circleci/classic:201808-01
#    working_directory: ~/my-project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./build/ci/install-deps

          #      - run:
#          name: Install Minikube
#          command: |
#            sudo minikube start --memory=4096 --vm-driver=none --kubernetes-version="v1.14.0" --extra-config=apiserver.v=10
#            sudo chown -R $USER ${HOME}/.{mini,}kube
#            kubectl config use-context minikube
#            build/ci/install-olm
#            eval $(sudo minikube docker-env)
      - run:
          name: Build
          command: ./build/ci/build-dev
#      - run:
#          name: Test Dev
#          command: ./build/ci/test-dev

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: circle-ci

