version: 2.1
jobs:
  build:
    machine: 
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Launch Kubernetes with microk8s
          command: |
            sudo snap install microk8s --classic --channel=1.16/stable
            # wait until a k8s node is ready
            sleep 10
            n=0
            until [ $n -ge 10 ]
            do
              (sudo /snap/bin/microk8s.kubectl get no | grep -z "Ready") && break
              n=$[$n+1]
              sleep 20
            done
            echo "Kubernetes cluster launched"
      - run:
          name: Run integration tests
          command: |
            sudo /snap/bin/microk8s.kubectl config > ~/.kube/config
            echo 'export KUBECONFIG=KUBECONFIG=~/.kube/config' >> $BASH_ENV
            sudo source $BASH_ENV
            sudo microk8s.kubectl cluster-info
            cat $KUBECONFIG
            sudo microk8s.kubectl get pods --all-namespaces

            sudo microk8s.kubectl apply -f \
              https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.12.0/crds.yaml

            sudo microk8s.kubectl apply -f \
            https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.12.0/olm.yaml

            sudo microk8s.kubectl rollout status -w deployment/olm-operator -n olm
            sudo microk8s.kubectl rollout status -w deployment/catalog-operator -n olm
            sudo microk8s.kubectl rollout status -w deployment/packageserver -n olm

            sudo microk8s.kubectl get pods --all-namespaces

workflows:
  version: 2
  build:
    jobs:
      - build
