version: 2.1
jobs:
  build:
    machine: 
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Install KinD
          command: |
            curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/0.1.0/kind-linux-amd64
            chmod +x kind
            sudo mv kind /usr/local/bin/
      - run:
          name: Create Kubernetes Cluster
          command: |
            kind create cluster
      - run:
          name: Install kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
      - run:
          name: Run Tests
          command: |
            echo "paula"
            kind get kubeconfig-path
            echo "susi"
            export KUBECONFIG="$(kind get kubeconfig-path)"
            kubectl cluster-info
            kubectl get pods --all-namespaces
workflows:
  version: 2
  build:
    jobs:
      - build
