version: 2.1
jobs:
  build:
    machine: 
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Install KinD
          command: |
            curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/0.1.0/kind-linux-amd64
            chmod +x kind
            sudo mv kind /usr/local/bin/
      - run:
          name: Create Kubernetes Cluster
          command: |
            kind create cluster
      - run:
          name: Install kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
      - run:
          name: Run Tests
          command: |
            echo "paula"
            kind get kubeconfig-path
            echo "susi"
            echo 'export KUBECONFIG=$(kind get kubeconfig-path)' >> $BASH_ENV
            source $BASH_ENV
            kind get clusters
            kubectl cluster-info
            cat $KUBECONFIG
            kubectl get pods --all-namespaces

            kubectl apply -f \
              https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.12.0/crds.yaml

            kubectl apply -f \
            https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.12.0/olm.yaml

            kubectl rollout status -w deployment/olm-operator -n olm
            kubectl rollout status -w deployment/catalog-operator -n olm
            kubectl rollout status -w deployment/packageserver -n olm

            kubectl get pods --all-namespaces

workflows:
  version: 2
  build:
    jobs:
      - build
