version: 2.1
jobs:
  build:
    machine: 
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Launch Kubernetes with microk8s
          command: |
            sudo snap install microk8s --classic --channel=1.16/stable
            sudo /snap/bin/microk8s.status --wait-ready --timeout=300
            sudo /snap/bin/microk8s.enable dns registry ingress
      - run:
          name: Run integration tests
          command: |
            sudo /snap/bin/microk8s.kubectl config view --raw > /tmp/kubeconfig
            echo 'export KUBECONFIG=/tmp/kubeconfig' >> $BASH_ENV
            source $BASH_ENV
            sudo snap install kubectl --classic
            kubectl --kubeconfig /tmp/kubeconfig
            kubectl cluster-info
            cat $KUBECONFIG
            kubectl get pods --all-namespaces

            kubectl apply -f \
              https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.12.0/crds.yaml

            kubectl apply -f \
            https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.12.0/olm.yaml

            kubectl rollout status -w deployment/olm-operator -n olm
            kubectl rollout status -w deployment/catalog-operator -n olm
            kubectl rollout status -w deployment/packageserver -n olm

            kubectl get pods --all-namespaces

workflows:
  version: 2
  build:
    jobs:
      - build
