version: 2.1
jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
#    working_directory: ~/my-project
    steps:
      - checkout
      - run:
          name: Use Python 3.6.5
          command: pyenv global 3.6.5
      - run:
          name: Install Dependencies
          command: ./build/ci/install-deps
      - run:
          name: Start Minikube
          command: ./build/ci/start-minikube
      - run:
          name: Install Operator Lifecycle Manager
          command: ./build/ci/install-olm
      - run:
          name: Build
          command: ./build/ci/build-dev
      - run:
          name: Test Dev
          command: ./build/ci/test-dev

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: circle-ci

