apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-rbac-cm
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.server.name }}
{{- if .Values.server.rbacConfig }}
data:
{{- toYaml .Values.server.rbacConfig | nindent 4 }}
{{- if .Values.openshift.enabled }}
{{- if .Values.openshift.oAuth.enabled }}
{{- if .Values.openshift.oAuth.rbac.enabled }}
      g, {{ .Values.openshift.oAuth.rbac.groups.developers.name }}, {{ .Values.openshift.oAuth.rbac.groups.developers.role }}
      g, {{ .Values.openshift.oAuth.rbac.groups.admins.name }}, {{ .Values.openshift.oAuth.rbac.groups.admins.role }}
{{- end }}
{{- end }}
{{- end }}
{{- else }}
{{- if .Values.openshift.enabled }}
{{- if .Values.openshift.oAuth.enabled }}
{{- if .Values.openshift.oAuth.rbac.enabled }}
data:
  policy.csv: |
      g, {{ .Values.openshift.oAuth.rbac.groups.developers.name }}, {{ .Values.openshift.oAuth.rbac.groups.developers.role }}
      g, {{ .Values.openshift.oAuth.rbac.groups.admins.name }}, {{ .Values.openshift.oAuth.rbac.groups.admins.role }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
