apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: argocd-operators-helm
  namespace: marketplace
spec:
  targetNamespaces:
  - marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: argocd-operators-helm
  namespace: marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: disposab1e
  displayName: "Argo CD Operators (Helm)"
  publisher: "Disposable Zone"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operators-helm
  namespace: marketplace
spec:
  channel: alpha
  name: argocd-operators-helm
  source: argocd-operators-helm
  sourceNamespace: marketplace
