{{- if .Values.dex.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "argo-cd.dexServiceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-{{ .Values.dex.name }}
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.dex.name }}
{{- if .Values.openshift.enabled }}
{{- if .Values.openshift.oAuth.enabled }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.argocd: {{ .Values.openshift.oAuth.config.redirect.url }}
{{- end }}
{{- end }}
{{- end }}

