apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: argocd-operator-helm
  namespace: argocd
spec:
  targetNamespaces:
  - argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/disposab1e/argocd-operator-helm-registry:0.0.2
  displayName: Argo CD Operator (Helm) Registry
  publisher: Disposable Zone
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator-helm
  namespace: argocd
spec:
  channel: alpha
  name: argocd-operator-helm
  source: argocd-catalog
  sourceNamespace: olm
