apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: argocd-operator-helm
  namespace: argocd
spec:
  targetNamespaces:
  - argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-serviceaccounts-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: argocd-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: quay.io/disposab1e/argocd-operator-helm-registry-ocp-dev:0.0.4
  displayName: Argo CD Operators
  publisher: Argo CD
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator-helm
  namespace: argocd
spec:
  channel: alpha
  name: argocd-operator-helm
  source: argocd-catalog
  sourceNamespace: olm
