name: build-and-test

on:
  pull_request:
    branches:
    - travis-ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: cd ${{ github.workspace }} && build/ci/install-deps

